"""Selection, grouping, iCalendar generation, and CLI."""

from __future__ import annotations

import argparse
import shlex
import sys
import sysconfig
import unicodedata
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from difflib import SequenceMatcher
from pathlib import Path
from typing import Iterable, Mapping, Sequence
from uuid import UUID, uuid5

from icalendar import Calendar, Event

from ._version import __version__
from .easter import MAX_YEAR, MIN_YEAR, orthodox_easter
from .models import Catalog, Nameday
from .parser import DataValidationError, load_catalog
from .rules import CustomRule, UnsupportedFeastRuleError, resolve_feast_date


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _default_data_path(filename: str) -> Path:
    """Locate YAML data in a source checkout or an installed distribution."""

    source_path = PROJECT_ROOT / "data" / filename
    if source_path.is_file():
        return source_path
    installed_path = (
        Path(sysconfig.get_path("data")) / "share" / "grecal" / filename
    )
    if installed_path.is_file():
        return installed_path
    return source_path


DEFAULT_FEASTS_PATH = _default_data_path("feasts.yaml")
DEFAULT_NAMES_PATH = _default_data_path("names.yaml")
DEFAULT_OBSERVANCES_PATH = _default_data_path("observances.yaml")
DEFAULT_CALENDAR_NAME = "Grecal — Greek Orthodox Calendar"
DEFAULT_CALENDAR_DESCRIPTION = (
    "Greek Orthodox namedays and church feasts generated by Grecal."
)
DEFAULT_CALENDAR_ID = "default"
GRECAL_UID_NAMESPACE = UUID("9a1511f8-6c55-51e0-a06e-f3b833e69315")


@dataclass(frozen=True)
class _YearStatistics:
    year: int
    identity_groups: int
    display_names: int
    church_feasts: int
    calendar_events: int


@dataclass(frozen=True)
class NameSearchResult:
    """A ranked catalog-name match returned by :func:`search_names`."""

    name: str
    nameday_id: str
    popularity: int
    score: float
    match_type: str


@dataclass(frozen=True)
class DateLookupResult:
    """Namedays and church observances resolved for one calendar date."""

    day: date
    namedays: tuple[str, ...]
    observances: tuple[str, ...]


def select_namedays(
    namedays: Iterable[Nameday],
    *,
    top: int | None = None,
    min_popularity: int | None = None,
) -> tuple[Nameday, ...]:
    """Select entries by rank or minimum popularity; no filters means all."""

    if top is not None and min_popularity is not None:
        raise ValueError("top and min_popularity are mutually exclusive")
    if top is not None and top < 1:
        raise ValueError("top must be at least 1")
    if min_popularity is not None and not 0 <= min_popularity <= 100:
        raise ValueError("min_popularity must be between 0 and 100")

    ordered = sorted(namedays, key=lambda item: (-item.popularity, item.id))
    if top is not None:
        return tuple(ordered[:top])
    if min_popularity is not None:
        return tuple(
            item for item in ordered if item.popularity >= min_popularity
        )
    return tuple(ordered)


def _normalized_name(name: str) -> str:
    """Return a case- and tonos-insensitive key for a display name."""

    return "".join(
        character
        for character in unicodedata.normalize("NFKD", name.strip()).casefold()
        if not unicodedata.combining(character)
    )


def _edit_distance(left: str, right: str) -> int:
    """Return an adjacent-transposition-aware edit distance."""

    rows = len(left) + 1
    columns = len(right) + 1
    distances = [[0] * columns for _ in range(rows)]
    for row in range(rows):
        distances[row][0] = row
    for column in range(columns):
        distances[0][column] = column

    for row in range(1, rows):
        for column in range(1, columns):
            substitution_cost = left[row - 1] != right[column - 1]
            distances[row][column] = min(
                distances[row - 1][column] + 1,
                distances[row][column - 1] + 1,
                distances[row - 1][column - 1] + substitution_cost,
            )
            if (
                row > 1
                and column > 1
                and left[row - 1] == right[column - 2]
                and left[row - 2] == right[column - 1]
            ):
                distances[row][column] = min(
                    distances[row][column],
                    distances[row - 2][column - 2] + 1,
                )
    return distances[-1][-1]


def _fuzzy_similarity(left: str, right: str) -> float:
    longest = max(len(left), len(right))
    if longest == 0:
        return 1.0
    edit_similarity = 1 - (_edit_distance(left, right) / longest)
    sequence_similarity = SequenceMatcher(
        None,
        left,
        right,
        autojunk=False,
    ).ratio()
    return (0.65 * edit_similarity) + (0.35 * sequence_similarity)


def search_names(
    catalog: Catalog,
    query: str,
    *,
    limit: int = 10,
) -> tuple[NameSearchResult, ...]:
    """Return ranked exact, partial, and fuzzy catalog-name matches."""

    normalized_query = _normalized_name(query)
    if not normalized_query:
        raise ValueError("search query must not be empty")
    if limit < 1:
        raise ValueError("limit must be at least 1")

    ranked: list[tuple[int, float, NameSearchResult]] = []
    for nameday in catalog.namedays:
        for display_name in nameday.names:
            normalized_display_name = _normalized_name(display_name)
            if normalized_display_name == normalized_query:
                category = 4
                score = 1.0
                match_type = "exact"
            elif normalized_display_name.startswith(normalized_query):
                category = 3
                score = len(normalized_query) / len(normalized_display_name)
                match_type = "prefix"
            elif normalized_query in normalized_display_name:
                category = 2
                score = len(normalized_query) / len(normalized_display_name)
                match_type = "substring"
            else:
                if len(normalized_query) < 3:
                    continue
                score = _fuzzy_similarity(
                    normalized_query,
                    normalized_display_name,
                )
                threshold = 0.58 if len(normalized_query) <= 4 else 0.55
                if score < threshold:
                    continue
                category = 1
                match_type = "fuzzy"

            result = NameSearchResult(
                name=display_name,
                nameday_id=nameday.id,
                popularity=nameday.popularity,
                score=score,
                match_type=match_type,
            )
            ranked.append((category, score, result))

    ranked.sort(
        key=lambda item: (
            -item[0],
            -item[1],
            -item[2].popularity,
            _normalized_name(item[2].name),
            item[2].nameday_id,
        )
    )
    return tuple(item[2] for item in ranked[:limit])


def select_namedays_by_name(
    catalog: Catalog,
    names: Iterable[str],
) -> tuple[Nameday, ...]:
    """Select requested display names, preserving their catalog spellings.

    Multiple requested variants from one identity group are returned as one
    ``Nameday`` carrying only those variants. Matching ignores case and Greek
    diacritics.
    """

    index: dict[str, tuple[Nameday, str]] = {}
    for nameday in catalog.namedays:
        for display_name in nameday.names:
            index[_normalized_name(display_name)] = (nameday, display_name)

    selected: dict[str, tuple[Nameday, list[str]]] = {}
    unknown: list[str] = []
    for requested_name in names:
        cleaned_name = requested_name.strip()
        match = index.get(_normalized_name(cleaned_name)) if cleaned_name else None
        if match is None:
            if cleaned_name not in unknown:
                unknown.append(cleaned_name or "<empty>")
            continue
        nameday, display_name = match
        if nameday.id not in selected:
            selected[nameday.id] = (nameday, [])
        selected_names = selected[nameday.id][1]
        if display_name not in selected_names:
            selected_names.append(display_name)

    if unknown:
        label = "name" if len(unknown) == 1 else "names"
        raise ValueError(
            f"{label} not found in the catalog: {', '.join(unknown)}"
        )
    if not selected:
        raise ValueError("at least one name is required")

    return tuple(
        Nameday(
            id=nameday.id,
            feast=nameday.feast,
            popularity=nameday.popularity,
            names=tuple(display_names),
        )
        for nameday, display_names in selected.values()
    )


def _generate_selected_namedays(
    catalog: Catalog,
    selected: Iterable[Nameday],
    from_year: int,
    to_year: int,
    *,
    custom_rules: Mapping[str, CustomRule] | None = None,
) -> dict[date, tuple[str, ...]]:
    if not MIN_YEAR <= from_year <= to_year <= MAX_YEAR:
        raise ValueError(
            f"year range must satisfy {MIN_YEAR} <= from_year <= to_year <= {MAX_YEAR}"
        )
    feasts = catalog.feast_map()
    grouped: dict[date, list[str]] = defaultdict(list)
    for year in range(from_year, to_year + 1):
        easter = orthodox_easter(year)
        for nameday in selected:
            celebration = resolve_feast_date(
                feasts[nameday.feast],
                year,
                easter,
                custom_rules=custom_rules,
            )
            for name in nameday.names:
                if name not in grouped[celebration]:
                    grouped[celebration].append(name)
    return {day: tuple(names) for day, names in sorted(grouped.items())}


def generate_namedays(
    catalog: Catalog,
    from_year: int,
    to_year: int,
    *,
    top: int | None = None,
    min_popularity: int | None = None,
    custom_rules: Mapping[str, CustomRule] | None = None,
) -> dict[date, tuple[str, ...]]:
    """Resolve and group selected names, returning at most one group per day."""

    selected = select_namedays(
        catalog.namedays, top=top, min_popularity=min_popularity
    )
    return _generate_selected_namedays(
        catalog,
        selected,
        from_year,
        to_year,
        custom_rules=custom_rules,
    )


def generate_personal_namedays(
    catalog: Catalog,
    names: Iterable[str],
    from_year: int,
    to_year: int,
    *,
    custom_rules: Mapping[str, CustomRule] | None = None,
) -> dict[date, tuple[str, ...]]:
    """Resolve only the requested display names for a personal calendar."""

    selected = select_namedays_by_name(catalog, names)
    return _generate_selected_namedays(
        catalog,
        selected,
        from_year,
        to_year,
        custom_rules=custom_rules,
    )


def generate_observances(
    catalog: Catalog,
    from_year: int,
    to_year: int,
    *,
    custom_rules: Mapping[str, CustomRule] | None = None,
) -> dict[date, tuple[str, ...]]:
    """Resolve and group church observance titles by date."""

    if not MIN_YEAR <= from_year <= to_year <= MAX_YEAR:
        raise ValueError(
            f"year range must satisfy {MIN_YEAR} <= from_year <= to_year <= {MAX_YEAR}"
        )
    feasts = catalog.feast_map()
    grouped: dict[date, list[str]] = defaultdict(list)
    for year in range(from_year, to_year + 1):
        easter = orthodox_easter(year)
        for observance in catalog.observances:
            celebration = resolve_feast_date(
                feasts[observance.feast],
                year,
                easter,
                custom_rules=custom_rules,
            )
            if observance.title not in grouped[celebration]:
                grouped[celebration].append(observance.title)
    return {day: tuple(titles) for day, titles in sorted(grouped.items())}


def lookup_date(
    catalog: Catalog,
    day: date,
    *,
    custom_rules: Mapping[str, CustomRule] | None = None,
) -> DateLookupResult:
    """Resolve all namedays and church observances for ``day``."""

    if not MIN_YEAR <= day.year <= MAX_YEAR:
        raise ValueError(f"date year must be between {MIN_YEAR} and {MAX_YEAR}")
    namedays = generate_namedays(
        catalog,
        day.year,
        day.year,
        custom_rules=custom_rules,
    ).get(day, ())
    observances = generate_observances(
        catalog,
        day.year,
        day.year,
        custom_rules=custom_rules,
    ).get(day, ())
    return DateLookupResult(
        day=day,
        namedays=namedays,
        observances=observances,
    )


def validate_catalog(
    catalog: Catalog,
    from_year: int = MIN_YEAR,
    to_year: int = MAX_YEAR,
    *,
    custom_rules: Mapping[str, CustomRule] | None = None,
) -> None:
    """Resolve every feast rule throughout a supported year range."""

    if not MIN_YEAR <= from_year <= to_year <= MAX_YEAR:
        raise ValueError(
            f"year range must satisfy {MIN_YEAR} <= from_year <= to_year <= {MAX_YEAR}"
        )
    for year in range(from_year, to_year + 1):
        easter = orthodox_easter(year)
        for feast in catalog.feasts:
            resolve_feast_date(
                feast,
                year,
                easter,
                custom_rules=custom_rules,
            )


def _calendar_uuid(calendar_id: str) -> UUID:
    return uuid5(GRECAL_UID_NAMESPACE, calendar_id)


def _calendar_uid(calendar_id: str) -> str:
    return f"urn:uuid:{_calendar_uuid(calendar_id)}"


def _event_uid(day: date, calendar_id: str) -> str:
    return f"urn:uuid:{uuid5(_calendar_uuid(calendar_id), day.isoformat())}"


def build_calendar(
    grouped_names: Mapping[date, Sequence[str]],
    *,
    grouped_observances: Mapping[date, Sequence[str]] | None = None,
    generated_at: datetime | None = None,
    calendar_name: str | None = DEFAULT_CALENDAR_NAME,
    calendar_description: str | None = DEFAULT_CALENDAR_DESCRIPTION,
    calendar_color: str | None = None,
    calendar_id: str = DEFAULT_CALENDAR_ID,
) -> Calendar:
    """Build a UTF-8 calendar with at most one all-day event per date."""

    stamp = generated_at or datetime.now(timezone.utc)
    if stamp.tzinfo is None:
        raise ValueError("generated_at must be timezone-aware")
    cleaned_calendar_id = calendar_id.strip()
    if not cleaned_calendar_id:
        raise ValueError("calendar_id must be a non-empty string")

    metadata = {
        "calendar_name": calendar_name,
        "calendar_description": calendar_description,
        "calendar_color": calendar_color,
    }
    cleaned_metadata: dict[str, str | None] = {}
    for field, value in metadata.items():
        if value is not None and not value.strip():
            raise ValueError(f"{field} must be a non-empty string")
        cleaned_metadata[field] = value.strip() if value is not None else None

    calendar = Calendar()
    calendar.add("prodid", "-//Grecal//Greek Orthodox Calendar//EL")
    calendar.add("version", "2.0")
    calendar.add("calscale", "GREGORIAN")
    calendar.add("uid", _calendar_uid(cleaned_calendar_id))
    if cleaned_metadata["calendar_name"] is not None:
        calendar.add("name", cleaned_metadata["calendar_name"])
        calendar.add("x-wr-calname", cleaned_metadata["calendar_name"])
    if cleaned_metadata["calendar_description"] is not None:
        calendar.add("description", cleaned_metadata["calendar_description"])
        calendar.add("x-wr-caldesc", cleaned_metadata["calendar_description"])
    calendar.add("last-modified", stamp.astimezone(timezone.utc))
    if cleaned_metadata["calendar_color"] is not None:
        calendar.add("color", cleaned_metadata["calendar_color"])

    observances = grouped_observances or {}
    days = sorted(set(grouped_names) | set(observances))
    for day in days:
        names = grouped_names.get(day, ())
        titles = observances.get(day, ())
        title_text = " · ".join(titles)
        names_text = ", ".join(names)
        summary = (
            f"{title_text} — {names_text}"
            if title_text and names_text
            else title_text or names_text
        )
        event = Event()
        event.add("uid", _event_uid(day, cleaned_calendar_id))
        event.add("dtstamp", stamp.astimezone(timezone.utc))
        event.add("summary", summary)
        event.add("dtstart", day)
        event.add("dtend", day + timedelta(days=1))
        calendar.add_component(event)
    return calendar


def write_calendar(calendar: Calendar, output_path: Path) -> None:
    """Serialize an iCalendar object as UTF-8 bytes."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(calendar.to_ical())


def _year_statistics(
    selected_namedays: Sequence[Nameday],
    grouped_names: Mapping[date, Sequence[str]],
    grouped_observances: Mapping[date, Sequence[str]],
    from_year: int,
    to_year: int,
    *,
    church_feast_count: int,
) -> tuple[_YearStatistics, ...]:
    identity_groups = len(selected_namedays)
    display_names = sum(len(item.names) for item in selected_namedays)
    event_days = set(grouped_names) | set(grouped_observances)
    return tuple(
        _YearStatistics(
            year=year,
            identity_groups=identity_groups,
            display_names=display_names,
            church_feasts=church_feast_count,
            calendar_events=sum(day.year == year for day in event_days),
        )
        for year in range(from_year, to_year + 1)
    )


def _selection_label(
    args: argparse.Namespace,
    selected_namedays: Sequence[Nameday],
) -> str:
    if args.feasts_only:
        return "church feasts only"
    if args.personal_names is not None:
        count = sum(len(item.names) for item in selected_namedays)
        label = f"{count} personal " + ("name" if count == 1 else "names")
    elif args.top is not None:
        label = f"top {args.top} nameday groups"
    elif args.min_popularity is not None:
        label = f"nameday popularity >= {args.min_popularity}"
    else:
        label = "all nameday groups"
    return f"{label} + church feasts" if args.include_feasts else label


def _default_calendar_id(
    args: argparse.Namespace,
    selected_namedays: Sequence[Nameday],
) -> str:
    if args.feasts_only:
        return "feasts"
    if args.personal_names is not None:
        names = sorted(
            {
                _normalized_name(name)
                for nameday in selected_namedays
                for name in nameday.names
            }
        )
        selection = f"personal:{','.join(names)}"
        return f"complete:{selection}" if args.include_feasts else selection
    if args.top is not None:
        selection = f"top:{args.top}"
    elif args.min_popularity is not None:
        selection = f"min-popularity:{args.min_popularity}"
    else:
        selection = "all"
    prefix = "complete" if args.include_feasts else "namedays"
    return f"{prefix}:{selection}"


def _default_calendar_metadata(
    args: argparse.Namespace,
    from_year: int,
    to_year: int,
) -> tuple[str, str]:
    years = (
        str(from_year) if from_year == to_year else f"{from_year}–{to_year}"
    )
    if args.feasts_only:
        name = "Grecal — Greek Orthodox Feasts"
        subject = "Greek Orthodox church feasts"
    elif args.include_feasts:
        name = DEFAULT_CALENDAR_NAME
        subject = "Greek Orthodox namedays and church feasts"
    elif args.personal_names is not None:
        name = "Grecal — Personal Namedays"
        subject = "Personal Greek Orthodox namedays"
    else:
        name = "Grecal — Greek Orthodox Namedays"
        subject = "Greek Orthodox namedays"
    return name, f"{subject} for {years}, generated by Grecal."


def _print_generation_summary(
    output_path: Path,
    selection_label: str,
    statistics: Sequence[_YearStatistics],
    *,
    dry_run_size: int | None = None,
) -> None:
    headers = (
        "Year",
        "Identity groups",
        "Display names",
        "Church feasts",
        "Calendar events",
    )
    rows: list[tuple[str, ...]] = [
        (
            str(item.year),
            str(item.identity_groups),
            str(item.display_names),
            str(item.church_feasts),
            str(item.calendar_events),
        )
        for item in statistics
    ]
    totals = tuple(
        sum(getattr(item, field) for item in statistics)
        for field in (
            "identity_groups",
            "display_names",
            "church_feasts",
            "calendar_events",
        )
    )
    rows.append(("Total occurrences", *(str(value) for value in totals)))
    if len(statistics) > 1:
        rows.append(
            (
                "Average/year",
                *(f"{value / len(statistics):.1f}" for value in totals),
            )
        )

    widths = [
        max(len(headers[index]), *(len(row[index]) for row in rows))
        for index in range(len(headers))
    ]

    def format_row(row: Sequence[str]) -> str:
        return "  ".join(
            value.ljust(widths[index])
            if index == 0
            else value.rjust(widths[index])
            for index, value in enumerate(row)
        )

    years = (
        str(statistics[0].year)
        if len(statistics) == 1
        else f"{statistics[0].year}-{statistics[-1].year}"
    )
    if dry_run_size is None:
        print(f"Generated: {output_path} ({output_path.stat().st_size:,} bytes)")
    else:
        print("Dry run: no file written")
        print(f"Would generate: {output_path} ({dry_run_size:,} bytes)")
    print(f"Years: {years}")
    print(f"Selection: {selection_label}")
    print()
    print(format_row(headers))
    print(format_row(tuple("-" * width for width in widths)))
    for row in rows:
        print(format_row(row))


def _main_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="grecal",
        usage="grecal [-h] [--version] COMMAND",
        description="Greek Orthodox nameday calendar tools.",
        epilog=(
            "commands:\n"
            "  generate  Generate an ICS calendar\n"
            "  find      Resolve one exact name\n"
            "  search    Search for possible names\n"
            "  date      Show namedays and observances for a date\n"
            "  validate  Validate catalog data and feast rules"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    parser.add_argument(
        "command",
        nargs="?",
        choices=("generate", "find", "search", "date", "validate"),
        help=argparse.SUPPRESS,
    )
    return parser


def _generation_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="grecal generate",
        description="Generate an ICS calendar of namedays and church feasts.",
    )
    selection = parser.add_mutually_exclusive_group(required=True)
    selection.add_argument(
        "--all",
        action="store_true",
        help="include every nameday identity group",
    )
    selection.add_argument(
        "--top",
        type=int,
        metavar="N",
        help="include the N highest-scoring identity groups (N >= 1)",
    )
    selection.add_argument(
        "--min-popularity",
        type=int,
        metavar="N",
        help="include groups with popularity >= N (0-100)",
    )
    selection.add_argument(
        "--feasts-only",
        action="store_true",
        help="include church feasts without namedays",
    )
    selection.add_argument(
        "--names",
        dest="personal_names",
        metavar="NAME[,NAME...]",
        help="include only these comma-separated names",
    )
    parser.add_argument(
        "--include-feasts",
        action="store_true",
        help="include church feasts alongside the selected namedays",
    )
    current_year = date.today().year
    parser.add_argument("--from-year", type=int, default=current_year)
    parser.add_argument("--to-year", type=int)
    parser.add_argument("--output", type=Path, default=Path("grecal.ics"))
    parser.add_argument(
        "--calendar-name",
        metavar="TEXT",
        help="calendar display name (default depends on selection)",
    )
    parser.add_argument(
        "--calendar-description",
        metavar="TEXT",
        help="calendar description (default depends on selection and years)",
    )
    parser.add_argument(
        "--calendar-color",
        metavar="COLOR",
        help="suggested calendar display color (for example: blue)",
    )
    parser.add_argument(
        "--calendar-id",
        metavar="ID",
        help="stable logical identity for calendar and event UIDs",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="calculate and report without writing an ICS file",
    )
    _add_data_path_arguments(parser)
    return parser


def _add_data_path_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    parser.add_argument(
        "--feasts-file",
        dest="feasts_path",
        type=Path,
        default=DEFAULT_FEASTS_PATH,
        help="path to feast definitions YAML",
    )
    parser.add_argument(
        "--names-file",
        dest="names_path",
        type=Path,
        default=DEFAULT_NAMES_PATH,
        help="path to namedays YAML",
    )
    parser.add_argument(
        "--observances-file",
        dest="observances_path",
        type=Path,
        default=DEFAULT_OBSERVANCES_PATH,
        help="path to church observances YAML",
    )


def _validation_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="grecal validate",
        description=(
            "Validate YAML data and resolve every feast rule for 1900-2100."
        ),
    )
    _add_data_path_arguments(parser)
    return parser


def _find_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="grecal find",
        description="Resolve one complete catalog name and its nameday dates.",
    )
    parser.add_argument("name", metavar="NAME", help="complete name to resolve")
    current_year = date.today().year
    parser.add_argument("--from-year", type=int, default=current_year)
    parser.add_argument("--to-year", type=int)
    _add_data_path_arguments(parser)
    return parser


def _search_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="grecal search",
        description="Search for names using partial and fuzzy matching.",
    )
    parser.add_argument("query", metavar="QUERY", help="name or fragment to search")
    parser.add_argument(
        "--limit",
        type=int,
        default=10,
        metavar="N",
        help="maximum results to return (default: 10)",
    )
    _add_data_path_arguments(parser)
    return parser


def _parse_date_argument(value: str) -> date:
    if value.casefold() == "today":
        return date.today()
    try:
        parsed = date.fromisoformat(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            "DATE must use YYYY-MM-DD format or be 'today'"
        ) from exc
    if parsed.isoformat() != value:
        raise argparse.ArgumentTypeError(
            "DATE must use YYYY-MM-DD format or be 'today'"
        )
    if not MIN_YEAR <= parsed.year <= MAX_YEAR:
        raise argparse.ArgumentTypeError(
            f"DATE year must be between {MIN_YEAR} and {MAX_YEAR}"
        )
    return parsed


def _date_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="grecal date",
        description="Show namedays and church observances for one date.",
    )
    parser.add_argument(
        "day",
        metavar="DATE",
        type=_parse_date_argument,
        help="date in YYYY-MM-DD format, or 'today'",
    )
    _add_data_path_arguments(parser)
    return parser


def _load_catalog_from_args(args: argparse.Namespace) -> Catalog:
    return load_catalog(
        args.feasts_path,
        args.names_path,
        args.observances_path,
    )


def _validate_main(argv: Sequence[str]) -> int:
    parser = _validation_argument_parser()
    args = parser.parse_args(argv)
    try:
        catalog = _load_catalog_from_args(args)
        validate_catalog(catalog)
    except (
        DataValidationError,
        OSError,
        UnsupportedFeastRuleError,
        ValueError,
    ) as exc:
        parser.exit(2, f"{parser.prog}: error: {exc}\n")

    print("Validation successful")
    print(f"Years checked: {MIN_YEAR}-{MAX_YEAR}")
    print(f"Feast definitions: {len(catalog.feasts)}")
    print(f"Identity groups: {len(catalog.namedays)}")
    print(
        "Display names: "
        f"{sum(len(nameday.names) for nameday in catalog.namedays)}"
    )
    print(f"Church feasts: {len(catalog.observances)}")
    return 0


def _generate_main(argv: Sequence[str]) -> int:
    parser = _generation_argument_parser()
    args = parser.parse_args(argv)
    if args.feasts_only and args.include_feasts:
        parser.error("--feasts-only cannot be combined with --include-feasts")
    to_year = args.to_year if args.to_year is not None else args.from_year
    try:
        catalog = _load_catalog_from_args(args)
        requested_names = (
            args.personal_names.split(",")
            if args.personal_names is not None
            else None
        )
        if args.feasts_only:
            selected_namedays = ()
            grouped_names = {}
        elif requested_names is not None:
            selected_namedays = select_namedays_by_name(
                catalog, requested_names
            )
            grouped_names = _generate_selected_namedays(
                catalog,
                selected_namedays,
                args.from_year,
                to_year,
            )
        else:
            selected_namedays = select_namedays(
                catalog.namedays,
                top=args.top,
                min_popularity=args.min_popularity,
            )
            grouped_names = generate_namedays(
                catalog,
                args.from_year,
                to_year,
                top=args.top,
                min_popularity=args.min_popularity,
            )
        grouped_observances = (
            generate_observances(catalog, args.from_year, to_year)
            if args.include_feasts or args.feasts_only
            else {}
        )
        default_calendar_name, default_calendar_description = (
            _default_calendar_metadata(args, args.from_year, to_year)
        )
        calendar_id = (
            _default_calendar_id(args, selected_namedays)
            if args.calendar_id is None
            else args.calendar_id
        )
        calendar = build_calendar(
            grouped_names,
            grouped_observances=grouped_observances,
            calendar_name=(
                default_calendar_name
                if args.calendar_name is None
                else args.calendar_name
            ),
            calendar_description=(
                default_calendar_description
                if args.calendar_description is None
                else args.calendar_description
            ),
            calendar_color=args.calendar_color,
            calendar_id=calendar_id,
        )
        dry_run_size = len(calendar.to_ical()) if args.dry_run else None
        if not args.dry_run:
            write_calendar(calendar, args.output)
        statistics = _year_statistics(
            selected_namedays,
            grouped_names,
            grouped_observances,
            args.from_year,
            to_year,
            church_feast_count=(
                len(catalog.observances)
                if args.include_feasts or args.feasts_only
                else 0
            ),
        )
        _print_generation_summary(
            args.output,
            _selection_label(args, selected_namedays),
            statistics,
            dry_run_size=dry_run_size,
        )
    except (
        DataValidationError,
        OSError,
        UnsupportedFeastRuleError,
        ValueError,
    ) as exc:
        parser.exit(2, f"{parser.prog}: error: {exc}\n")
    return 0


def _find_main(argv: Sequence[str]) -> int:
    parser = _find_argument_parser()
    args = parser.parse_args(argv)
    to_year = args.to_year if args.to_year is not None else args.from_year
    try:
        catalog = _load_catalog_from_args(args)
        try:
            selected_namedays = select_namedays_by_name(catalog, (args.name,))
        except ValueError as exc:
            command = f"grecal search {shlex.quote(args.name)}"
            parser.exit(
                2,
                f"{parser.prog}: error: {exc}\nTry: {command}\n",
            )
        grouped_names = _generate_selected_namedays(
            catalog,
            selected_namedays,
            args.from_year,
            to_year,
        )
        selected = selected_namedays[0]
        source_nameday = next(
            item for item in catalog.namedays if item.id == selected.id
        )
    except (
        DataValidationError,
        OSError,
        UnsupportedFeastRuleError,
        ValueError,
    ) as exc:
        parser.exit(2, f"{parser.prog}: error: {exc}\n")

    print(f"Name: {selected.names[0]}")
    print(f"Identity group: {selected.id}")
    print(f"Variants: {', '.join(source_nameday.names)}")
    print("Dates:")
    for day in grouped_names:
        print(f"  {day.isoformat()}")
    return 0


def _search_main(argv: Sequence[str]) -> int:
    parser = _search_argument_parser()
    args = parser.parse_args(argv)
    try:
        catalog = _load_catalog_from_args(args)
        results = search_names(catalog, args.query, limit=args.limit)
    except (
        DataValidationError,
        OSError,
        ValueError,
    ) as exc:
        parser.exit(2, f"{parser.prog}: error: {exc}\n")

    if not results:
        print(f"No matching names found for: {args.query}")
        return 1
    for result in results:
        print(f"{result.name}  group: {result.nameday_id}")
    return 0


def _date_main(argv: Sequence[str]) -> int:
    parser = _date_argument_parser()
    args = parser.parse_args(argv)
    try:
        catalog = _load_catalog_from_args(args)
        result = lookup_date(catalog, args.day)
    except (
        DataValidationError,
        OSError,
        UnsupportedFeastRuleError,
        ValueError,
    ) as exc:
        parser.exit(2, f"{parser.prog}: error: {exc}\n")

    print(f"Date: {result.day.isoformat()}")
    print(f"Namedays: {', '.join(result.namedays) if result.namedays else 'none'}")
    print(
        "Church observances: "
        + (", ".join(result.observances) if result.observances else "none")
    )
    return 0 if result.namedays or result.observances else 1


def main(argv: Sequence[str] | None = None) -> int:
    arguments = tuple(sys.argv[1:] if argv is None else argv)
    if not arguments:
        _main_argument_parser().print_help()
        return 0

    command_handlers = {
        "generate": _generate_main,
        "find": _find_main,
        "search": _search_main,
        "date": _date_main,
        "validate": _validate_main,
    }
    handler = command_handlers.get(arguments[0])
    if handler is not None:
        return handler(arguments[1:])

    parser = _main_argument_parser()
    if arguments[0].startswith("-") and arguments[0] not in {
        "-h",
        "--help",
        "--version",
    }:
        parser.error(
            f"unrecognized argument: {arguments[0]}; "
            "generation options require 'grecal generate'"
        )
    parser.parse_args(arguments)
    return 0
